---
version: "2"
plugins:
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - php
  eslint:
    enabled: true
    channel: "eslint-6"
    config:
      config: ./.eslintrc.js
    extensions:
      - .es6
      - .js
      - .ts
  fixme:
    enabled: true
  rubocop:
    enabled: true
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  method-complexity:
    config:
      threshold: 5
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  method-count:
    config:
      threshold: 20
  file-lines:
    config:
      threshold: 500
  method-lines:
    enabled: false
exclude_patterns:
  - config/
  - db/
  - dist/
  - features/
  - "**/node_modules/"
  - script/
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - Tests/
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/__tests__/"
  - "**/__mocks__/"
