name: Build/release

on: push

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: registry.gitlab.com
  DOCKER_IMAGE: telios2/telios-devops/ansible/prd:latest

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16
                   
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}

      - name: check for build artifacts
        shell: bash
        run: |
          ls -la release/

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: check for build artifacts
        shell: bash
        run: |
          docker pull ${{ env.REGISTRY }}/{{ env.DOCKER_IMAGE }}