name: Build and Publish

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
      os_type:
        required: true
        type: string
#    secrets:
#      SPACES_ACCESS_KEY:
#        required: true
#      SPACES_SECRET_KEY
#        required: true
jobs:
  build:
    runs-on: ${{ inputs.os_type }}
#    runs-on: ${{ matrix.os }}
    needs: set_version
#TODO Don't use the matrix build so that succsful builds can be published without waiting, instead make two additional files for common code of the jobs and make 6 separate jobs
#    strategy:
#      matrix:
#        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          submodules: true

      - uses: actions/download-artifact@v2
        with:
          name: package_json
          path: ./

      - name: check artifacts
        shell: bash
        run: |
          cat app/package.json

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

#      - name: Yarn install and build
#        shell: bash
#       run: |
#         yarn install

#TODO will periodically fail to build, try to cache the node_modules / binaries to avoid recompiles
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: false

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.build_type }} #${{ matrix.os }}
          path: release/

  publish:
    if: github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/telios2/telios-devops/ansible/prd:latest
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    needs: build

    strategy:
      matrix:   
        os: [macos-latest, ubuntu-latest, windows-latest]
      
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: actions/download-artifact@v2
        with:
          name: package_json
          path: ./

      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.build_type }} #${{ matrix.os }}
          path: release/

      - name: ansible publish
        shell: bash
        run: |
          ls -la release/
          echo ${{ inputs.build_type }}
          ansible-playbook playbooks/site.yml --tags none
